Repository spyder-ide/qtpy, pull requests merged in 2021-12, with the labels that each got.

#289 PR: Add warning for deprecated/EoL Qt5 & PyQt5/PySide2 versions to fix #284
  qtpy/__init__.py
Labels: type:Task

#290 PR: Import all classes in QtTest module.
  qtpy/QtTest.py
  qtpy/tests/test_qttest.py
Labels: type:Enhancement

#292 PR: Define Qt/binding versions at top level, fix warnings if versions not found, and fix test dir on CIs
  .github/workflows/ci.yml
  .github/workflows/test.sh
  qtpy/__init__.py
Labels: type:Bug

#293 PR: Update RELEASE.md for 1.x version
  RELEASE.md
Labels: type:Task

#278 PR: Update gitignore, gitattributes, license, authors and security policy
  .gitattributes
  .gitignore
  AUTHORS.md
  LICENSE.txt
  MANIFEST.in
  SECURITY.md
Labels: type:Task

#294 PR: Add minimum version check for Qt6 >=6.2.0
  qtpy/__init__.py
Labels: type:Task

#296 PR: Add support for Python 3.10 on CIs and packaging
  .github/workflows/ci.yml
  .github/workflows/test.sh
  qtpy/tests/test_uic.py
  setup.cfg
Labels: type:Task

#301 PR: Update README.md adding a line for QtPy usefulness when migrating between Qt bindings/versions
  README.md
Labels: type:Task

#303 PR: Fix QFileSystemModel for PyQt6
  qtpy/QtWidgets.py
Labels: type:Bug

#309 PR: Set CI job's timeout to 10 min to force a stalled test to terminate
  .github/workflows/ci.yml
Labels: type:Task
