Repository spyder-ide/qtpy, pull requests merged in 2021-11, with the labels that each got.

#268 PR: Fix and improve Coveralls reporting
  .github/workflows/ci.yml
  .github/workflows/test.sh
Labels: type:Task

#273 PR: Prevent future deprecations messages and decrease general technical debt + code style issues
  qtpy/QtCharts.py
  qtpy/QtCore.py
  qtpy/__init__.py
  qtpy/tests/test_qtcore.py
  qtpy/tests/test_qtdesigner.py
  qtpy/tests/test_qtsvg.py
  qtpy/tests/test_uic.py
  qtpy/uic.py
Labels: type:Task

#276 PR: Fix regression in FORCE_QT_API behavior from merging PySide6 support
  qtpy/__init__.py
Labels: type:Bug

#279 PR: Add back legacy PYQT4 and PYSIDE package-level constants for compat
  qtpy/__init__.py
Labels: type:Task

#277 PR: Add Contributing Guide based on other Spyder projects
  CONTRIBUTING.md
Labels: type:Task

#281 PR: Catch `PythonQtError` when trying to do alias for `QtDataVisualization` and dev version correction
  qtpy/__init__.py
  qtpy/_version.py
Labels: type:Bug

#283 PR: Add a warning for developers still running legacy Qt4-based APIs
  .github/workflows/ci.yml
  qtpy/__init__.py
Labels: type:Task

#282 PR: Update README sponsors section
  README.md
Labels: type:Task

#285 PR: Import Callable and MutableMapping in py3compat for Python 2 compat
  qtpy/py3compat.py
Labels: type:Bug

#272 PR: Upgrade packaging to avoid legacy/deprecated behavior and follow PEP 517
  .github/workflows/ci.yml
  .github/workflows/test.sh
  RELEASE.md
  pyproject.toml
  qtpy/__init__.py
  qtpy/_version.py
  setup.cfg
  setup.py
Labels: type:Task

#287 PR: Map exec_ to their non-deprecated alternatives
  qtpy/QtCore.py
  qtpy/QtGui.py
  qtpy/QtPrintSupport.py
  qtpy/QtSql.py
  qtpy/QtWidgets.py
Labels: type:Enhancement
