Repository spyder-ide/qtpy, pull requests merged in 2022-04, with the labels that each got.

#331 PR: Use QFileDialog.Option to be compatiable with Qt6
  qtpy/compat.py
Labels: type:Bug

#333 PR: Skip import of QOpenGLTime* on architectures where not available
  qtpy/QtOpenGL.py
  qtpy/tests/test_qtopengl.py
Labels: type:Bug

#334 PR: Remove `QHeaderView` patch related files
  qtpy/_patch/__init__.py
  qtpy/_patch/qheaderview.py
  qtpy/tests/test_patch_qheaderview.py
Labels: type:Task

#335 PR: Fix uic skipped tests and PyQt 6.3.0 segfaulting tests
  .github/workflows/ci.yml
  .github/workflows/test.sh
  qtpy/tests/test_uic.py
Labels: type:Bug

#337 PR: Add command line support for Mypy
  MANIFEST.in
  README.md
  qtpy/__init__.py
  qtpy/__main__.py
  qtpy/cli.py
  qtpy/py.typed
  qtpy/tests/test_cli.py
  setup.cfg
Labels: type:Enhancement

#341 PR: Add workaround for `mode` argument in QTextCursor.movePosition (Pyside2)
  qtpy/QtGui.py
  qtpy/tests/test_qtgui.py
Labels: type:Enhancement

#340 PR: Fix bug with environ handling
  qtpy/__init__.py
  qtpy/tests/conftest.py
  qtpy/tests/test_main.py
Labels: type:Bug
