Repository spyder-ide/qtpy, pull requests merged in 2022-08, with the labels that each got.

#360 CI: Ensure conda-forge channel usage when testing with conda
  .github/workflows/ci.yml
Labels: type:Task

#361 PR: toPython helpers for QDate and QTime
  qtpy/QtCore.py
  qtpy/tests/test_qtcore.py
Labels: type:Enhancement

#363 PR: Fix typo in Qt flags in Readme
  README.md
Labels: type:Bug
