Repository spyder-ide/qtpy, pull requests merged in 2022-07, with the labels that each got.

#353 PR: Add note to readme about use with Pyright
  README.md
Labels: type:Task

#354 PR: Add wrapper around sip/shiboken isdeleted/isvalid (compat.py)
  qtpy/compat.py
  qtpy/tests/test_compat.py
Labels: type:Enhancement

#358 PR: Fix PyQt6 typing import for Qt
  qtpy/QtCore.py
Labels: type:Bug

#357 PR: Add initial `Methods, helpers and QtPy namespace specifics` section to the README
  README.md
Labels: type:Task
