Repository spyder-ide/qtpy, pull requests merged in 2022-10, with the labels that each got.

#372 PR: Add `Qsci` to the imports
  .github/workflows/ci.yml
  .github/workflows/test.sh
  qtpy/Qsci.py
  qtpy/tests/test_qsci.py
Labels: type:Enhancement

#374 Don't re-assign Qt.MouseButton.MiddleButton on PySide6
  qtpy/QtCore.py
Labels: type:Bug

#380 PR: Enable more qt6 tests
  .github/workflows/ci.yml
  qtpy/tests/test_qt3danimation.py
  qtpy/tests/test_qtmultimediawidgets.py
  qtpy/tests/test_qtpositioning.py
  qtpy/tests/test_qtqml.py
  qtpy/tests/test_qtquick.py
  qtpy/tests/test_qtquickwidgets.py
  qtpy/tests/test_qtwebchannel.py
  qtpy/tests/test_qtwebsockets.py
Labels: type:Task
