Repository spyder-ide/qtpy, pull requests merged in 2022-01, with the labels that each got.

#307 PR: Add missing imports in QtOpenGL
  qtpy/QtGui.py
  qtpy/QtOpenGL.py
  qtpy/tests/test_qtopengl.py
Labels: type:Bug

#313 PR: Add missing `QtGui` utility function to `QtCore.Qt` for PySide bindings
  .github/workflows/ci.yml
  .github/workflows/test.sh
  qtpy/QtCore.py
  qtpy/tests/test_qtcore.py
  setup.cfg
Labels: type:Bug

#314 PR: Add mapping for missing enum values aliases on `QtCore.Qt`
  qtpy/QtCore.py
  qtpy/tests/test_qtcore.py
Labels: type:Bug

#308 PR: Fix mappings of instance method and slot alias (PyQt6 and PySide6)
  qtpy/QtCore.py
  qtpy/QtGui.py
  qtpy/QtPrintSupport.py
  qtpy/QtSql.py
  qtpy/QtWidgets.py
Labels: type:Bug

#315 PR: Add `QtCharts` alias for backward compatibility with 1.x
  qtpy/QtCharts.py
  qtpy/tests/test_qtcharts.py
Labels: type:Enhancement

#319 PR: Promote enum aliases
  qtpy/QtCore.py
  qtpy/enums_compat.py
  qtpy/tests/test_qtcore.py
  qtpy/tests/test_qtwidgets.py
Labels: type:Bug

#317 PR: Add missing tests for aliased methods
  .github/workflows/test.sh
  qtpy/QtCore.py
  qtpy/QtGui.py
  qtpy/tests/conftest.py
  qtpy/tests/test_qtcore.py
  qtpy/tests/test_qtgui.py
  qtpy/tests/test_qtmultimediawidgets.py
  qtpy/tests/test_qtprintsupport.py
  qtpy/tests/test_qtsql.py
  qtpy/tests/test_qtwidgets.py
  qtpy/tests/test_qtwinextras.py
  qtpy/tests/test_uic.py
  qtpy/tests/utils.py
  setup.cfg
Labels: type:Task
