Repository spyder-ide/qtpy, pull requests merged in 2023-07, with the labels that each got.

#431 PR: Rename `utils.py` to `_utils.py` to make it private
  qtpy/QtCore.py
  qtpy/QtGui.py
  qtpy/QtWidgets.py
  qtpy/_utils.py
  qtpy/tests/optional_deps/__init__.py
Labels: type:Task

#438 Make `exec()` for PySide2
  qtpy/QtCore.py
  qtpy/_utils.py
  qtpy/tests/test_qtcore.py
Labels: type:Enhancement

#440 PR: Replace custom implementation with loadUiType from PySide6
  qtpy/tests/test_uic.py
  qtpy/uic.py
Labels: type:Bug
