Repository spyder-ide/qtpy, pull requests merged in 2024-10, with the labels that each got.

#495 PR: Help users understand why PySide 6.8.0 gives a segfault
  qtpy/__init__.py
Labels: type:Enhancement

#497 Replace Quansight logo by CZI one in Readme
  README.md
Labels: type:Task

#475 PR: Add `QtCore.Qt.MouseButton.MidButton` alias for Qt6
  qtpy/QtCore.py
  qtpy/tests/test_qtcore.py
Labels: type:Bug
